language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - curl https://raw.githubusercontent.com/AstromechZA/spiro/master/install.sh | bash
script:
  - set -e
  - mkdir demo
  - ./spiro ./\{\{.package_name\}\} ./spec.yaml demo
  - cd demo/hello-world
  - cat setup.py
  - python setup.py develop
  - python setup.py test
  - pip install .[test]
  - python setup.py check -ms
